apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: dev-app
  ports:
  - protocol: TCP 
    port: 5001
    targetPort: 5001
    nodePort: 30007